spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/first_project2
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
file:
  directory: D:\2024_BACK_JI\download\first_project2

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
  cache:
    disabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_odd_first_4
    username: odd_first_4
    password: cell

file:
  directory: /home/download